"""Framework-neutral posture analysis primitives."""

from goodposture.core.alert_policy import (
    ALERT_POLICY_CONFIG_VERSION,
    DEFAULT_ALERT_POLICY_CONFIG,
    SUPPORTIVE_PROMPT_MESSAGE,
    AlertDecision,
    AlertEvent,
    AlertPolicy,
    AlertPolicyConfig,
    AlertState,
    AlertTrigger,
)
from goodposture.core.calibration import (
    CALIBRATION_CONFIG_VERSION,
    CALIBRATION_SCHEMA_VERSION,
    FEATURE_SCHEMA_VERSION,
    CalibrationAccumulator,
    CalibrationBaseline,
    CalibrationConfig,
    CalibrationFailure,
    CalibrationFeature,
    CalibrationProgress,
    CalibrationResult,
    CalibrationValidity,
)
from goodposture.core.metrics import extract_posture_metrics
from goodposture.core.models import (
    Landmark,
    LandmarkName,
    MetricReading,
    ObservationFailure,
    PoseObservation,
    PostureMetrics,
)
from goodposture.core.scoring import (
    DEFAULT_SCORING_CONFIG,
    SCORING_CONFIG_VERSION,
    FeatureDeviation,
    FeatureScoringRule,
    ScoreReading,
    ScoreResult,
    ScoreState,
    ScoringConfig,
    TimeAwareScoreSmoother,
    score_posture,
)

__all__ = [
    "ALERT_POLICY_CONFIG_VERSION",
    "CALIBRATION_CONFIG_VERSION",
    "CALIBRATION_SCHEMA_VERSION",
    "FEATURE_SCHEMA_VERSION",
    "CalibrationAccumulator",
    "CalibrationBaseline",
    "CalibrationConfig",
    "CalibrationFailure",
    "CalibrationFeature",
    "CalibrationProgress",
    "CalibrationResult",
    "CalibrationValidity",
    "DEFAULT_ALERT_POLICY_CONFIG",
    "DEFAULT_SCORING_CONFIG",
    "SCORING_CONFIG_VERSION",
    "FeatureDeviation",
    "FeatureScoringRule",
    "SUPPORTIVE_PROMPT_MESSAGE",
    "AlertDecision",
    "AlertEvent",
    "AlertPolicy",
    "AlertPolicyConfig",
    "AlertState",
    "AlertTrigger",
    "Landmark",
    "LandmarkName",
    "MetricReading",
    "ObservationFailure",
    "PoseObservation",
    "PostureMetrics",
    "ScoreReading",
    "ScoreResult",
    "ScoreState",
    "ScoringConfig",
    "TimeAwareScoreSmoother",
    "extract_posture_metrics",
    "score_posture",
]
